# Generated by Django 5.0.3 on 2024-04-15 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catetory',
            new_name='Category',
        ),
    ]
