# Generated by Django 5.0.3 on 2024-06-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0005_banner_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(unique=True, upload_to='category_images'),
        ),
    ]
