# Generated by Django 5.0.3 on 2024-04-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_img_1',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='ticket_image',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_images/'),
        ),
    ]
