# Generated by Django 5.0.3 on 2024-04-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_status_event_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
