# Generated by Django 5.0.3 on 2024-04-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('used', 'Used'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
