# Generated by Django 5.0.3 on 2024-04-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_ticket_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('used', 'Used'), ('pending', 'Pending'), ('disabled', 'Disabled')], default='pending', max_length=10),
        ),
    ]
