# Generated by Django 5.0.3 on 2024-08-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_payment_ticket_payment_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ticket_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
