# Generated by Django 5.0.3 on 2024-04-16 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_name', models.CharField(max_length=255, unique=True)),
                ('pan_card_number', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('GSTIN', models.BooleanField(default=False)),
                ('ITR', models.BooleanField(default=False)),
                ('contact_name', models.CharField(max_length=255)),
                ('benificiary_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('current', 'Current Account'), ('saving', 'Savings Account'), ('joint', 'Joint Account')], max_length=100)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('IFSC_code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vendor_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor'),
        ),
    ]
