# Generated by Django 5.0.3 on 2024-04-16 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_vendor_customuser_is_vendor_customuser_vendor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='is_active',
        ),
        migrations.AddField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
