# Generated by Django 5.0.3 on 2024-08-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='account_type',
            field=models.CharField(choices=[('current', 'Current Account'), ('savings', 'Savings Account'), ('joint', 'Joint Account')], max_length=100),
        ),
    ]
