# Generated by Django 5.0.3 on 2024-04-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='account_type',
            field=models.CharField(choices=[('current', 'Current Account'), ('saving', 'Savings Account'), ('joint', 'Joint Account')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
