# Generated by Django 5.0.3 on 2024-04-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendor_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
