# Generated by Django 5.0.3 on 2024-04-16 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendortoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorToken',
        ),
    ]
