# Generated by Django 5.0.3 on 2024-04-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_delete_vendortoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
